version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: kiosk
      POSTGRES_PASSWORD: tally
      POSTGRES_DB: kiosk
