server:
  shutdown: graceful

spring:
  profiles:
    active: local

  datasource:
    hikari:
      connection-timeout: 3000
      validation-timeout: 1000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

